import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // Agent tooling checks whole copies of this repo out under these two, each
  // with its own tsconfig. Left in, typescript-eslint finds several candidate
  // roots and then refuses to parse anything at all, including the real `src`.
  globalIgnores([
    'dist',
    'src-tauri/target',
    '.freebuff',
    '.claude',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
  },
  {
    // shadcn generates these; they export variant helpers alongside the
    // component and are regenerated by the CLI, so they aren't ours to edit.
    files: ['src/components/ui/**/*.tsx'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
])
